// need gdal/ogr2ogr in the lambda
service: berlin-fis-api

provider:
  name: aws
  runtime: nodejs8.10
  profile: prototypefund
  region: eu-central-1

package:
  include:
    - handler.js
    - convert.js
    - info.js
    - utils.js
    - download.js
    - package.json
    - yarn.lock

functions:
  getInfo:
    handler: handler.getInfo
  download:
    handler: handler.download
    memorySize: 1536
    timeout: 20

